language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1
      
    - php: 7.0
      env: THUMBER_DRIVER=gd

    - php: 7.0
      env: COVERAGE=1

    - php: 7.0
      env: CAKEPHP_VERSION="3.4.*"

install:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ ! -z "$CAKEPHP_VERSION" ]]; then composer require --update-with-dependencies cakephp/cakephp:${CAKEPHP_VERSION}; fi

script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' && $CAKEPHP_VERSION != '3.4.*' ]]; then vendor/bin/phpunit --exclude-group imageEquals; fi
  - if [[ $PHPCS != '1' && $COVERAGE != '1' && $CAKEPHP_VERSION = '3.4.*' ]]; then vendor/bin/phpunit --testsuite cakephp3.4 --exclude-group imageEquals; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=phpcs.xml.dist; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --exclude-group imageEquals --coverage-clover=clover.xml; fi
  
after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
