language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.2
      env: PHPCS=1
    - php: 7.2
      env: THUMBER_DRIVER=gd
    - php: 7.2
      env: COVERAGE=1

install:
  - printf "\n" | pecl install imagick
  - composer self-update -q
  - composer install --prefer-dist --no-interaction
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - composer show -i

script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' ]]; then vendor/bin/phpunit --exclude-group imageEquals; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=phpcs.xml.dist; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --exclude-group imageEquals --coverage-clover=clover.xml; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
